version: '3.4'

services:
  ipfs_host:
    image: 'ipfs/go-ipfs:latest'
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ./docker-volume/export:/export
      - ./docker-volume/data/ipfs:/data/ipfs
    expose:
      - 4001
      - 5001
      - 8080
# docker run -d --name ipfs_host -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest
